services:
  # Webサービスの設定
  - type: web
    name: stock-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --chdir src src.app:app"
    disk:
      name: my-disk
      path: /var/data
    envVars:
      # ... (環境変数) ...
      - key: PORT
        value: 10000

  # ワーカー: モデル学習のみを担当
  - type: worker
    name: model-trainer
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -c 'from src.app import train_and_save_model; train_and_save_model()'"
    disk:
      name: my-disk
      path: /var/data
    envVars:
      # ... (環境変数) ...